"""initial_schema

Revision ID: 2e9bd115ef4a
Revises: 
Create Date: 2025-10-25 15:14:20.143200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e9bd115ef4a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'EDITING', 'REVIEW', 'COMPLETED', name='project_status'), nullable=False),
    sa.Column('thumbnail_path', sa.String(length=512), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=False)
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'], unique=False)
    op.create_table('background_music',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('bpm', sa.Integer(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('license', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_background_music_id'), 'background_music', ['id'], unique=False)
    op.create_index(op.f('ix_background_music_project_id'), 'background_music', ['project_id'], unique=False)
    op.create_table('export_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('job_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('output_format', sa.String(length=50), nullable=False),
    sa.Column('output_path', sa.String(length=512), nullable=True),
    sa.Column('resolution', sa.String(length=20), nullable=True),
    sa.Column('bitrate', sa.Integer(), nullable=True),
    sa.Column('fps', sa.Integer(), nullable=True),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_export_jobs_id'), 'export_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_export_jobs_project_id'), 'export_jobs', ['project_id'], unique=False)
    op.create_index(op.f('ix_export_jobs_status'), 'export_jobs', ['status'], unique=False)
    op.create_table('video_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('fps', sa.Float(), nullable=True),
    sa.Column('codec', sa.String(length=50), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_assets_id'), 'video_assets', ['id'], unique=False)
    op.create_index(op.f('ix_video_assets_project_id'), 'video_assets', ['project_id'], unique=False)
    op.create_table('audio_tracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('video_asset_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('track_type', sa.String(length=20), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('sample_rate', sa.Integer(), nullable=True),
    sa.Column('channels', sa.Integer(), nullable=True),
    sa.Column('codec', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['video_asset_id'], ['video_assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audio_tracks_id'), 'audio_tracks', ['id'], unique=False)
    op.create_index(op.f('ix_audio_tracks_project_id'), 'audio_tracks', ['project_id'], unique=False)
    op.create_index(op.f('ix_audio_tracks_video_asset_id'), 'audio_tracks', ['video_asset_id'], unique=False)
    op.create_table('job_progress_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('export_job_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('metadata', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['export_job_id'], ['export_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_progress_logs_export_job_id'), 'job_progress_logs', ['export_job_id'], unique=False)
    op.create_index(op.f('ix_job_progress_logs_id'), 'job_progress_logs', ['id'], unique=False)
    op.create_table('scene_detections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('video_asset_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('scene_type', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('thumbnail_path', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['video_asset_id'], ['video_assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scene_detections_id'), 'scene_detections', ['id'], unique=False)
    op.create_index(op.f('ix_scene_detections_project_id'), 'scene_detections', ['project_id'], unique=False)
    op.create_index(op.f('ix_scene_detections_video_asset_id'), 'scene_detections', ['video_asset_id'], unique=False)
    op.create_table('timeline_clips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('video_asset_id', sa.Integer(), nullable=True),
    sa.Column('track_number', sa.Integer(), nullable=False),
    sa.Column('track_type', sa.String(length=20), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.Column('source_start', sa.Float(), nullable=False),
    sa.Column('source_end', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('muted', sa.Boolean(), nullable=False),
    sa.Column('locked', sa.Boolean(), nullable=False),
    sa.Column('transition_in', sa.String(length=50), nullable=True),
    sa.Column('transition_out', sa.String(length=50), nullable=True),
    sa.Column('effects', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['video_asset_id'], ['video_assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timeline_clips_id'), 'timeline_clips', ['id'], unique=False)
    op.create_index(op.f('ix_timeline_clips_project_id'), 'timeline_clips', ['project_id'], unique=False)
    op.create_index(op.f('ix_timeline_clips_video_asset_id'), 'timeline_clips', ['video_asset_id'], unique=False)
    op.create_table('subtitle_segments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('video_asset_id', sa.Integer(), nullable=True),
    sa.Column('timeline_clip_id', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('format', sa.String(length=20), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('speaker', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['timeline_clip_id'], ['timeline_clips.id'], ),
    sa.ForeignKeyConstraint(['video_asset_id'], ['video_assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subtitle_segments_id'), 'subtitle_segments', ['id'], unique=False)
    op.create_index(op.f('ix_subtitle_segments_project_id'), 'subtitle_segments', ['project_id'], unique=False)
    op.create_index(op.f('ix_subtitle_segments_timeline_clip_id'), 'subtitle_segments', ['timeline_clip_id'], unique=False)
    op.create_index(op.f('ix_subtitle_segments_video_asset_id'), 'subtitle_segments', ['video_asset_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subtitle_segments_video_asset_id'), table_name='subtitle_segments')
    op.drop_index(op.f('ix_subtitle_segments_timeline_clip_id'), table_name='subtitle_segments')
    op.drop_index(op.f('ix_subtitle_segments_project_id'), table_name='subtitle_segments')
    op.drop_index(op.f('ix_subtitle_segments_id'), table_name='subtitle_segments')
    op.drop_table('subtitle_segments')
    op.drop_index(op.f('ix_timeline_clips_video_asset_id'), table_name='timeline_clips')
    op.drop_index(op.f('ix_timeline_clips_project_id'), table_name='timeline_clips')
    op.drop_index(op.f('ix_timeline_clips_id'), table_name='timeline_clips')
    op.drop_table('timeline_clips')
    op.drop_index(op.f('ix_scene_detections_video_asset_id'), table_name='scene_detections')
    op.drop_index(op.f('ix_scene_detections_project_id'), table_name='scene_detections')
    op.drop_index(op.f('ix_scene_detections_id'), table_name='scene_detections')
    op.drop_table('scene_detections')
    op.drop_index(op.f('ix_job_progress_logs_id'), table_name='job_progress_logs')
    op.drop_index(op.f('ix_job_progress_logs_export_job_id'), table_name='job_progress_logs')
    op.drop_table('job_progress_logs')
    op.drop_index(op.f('ix_audio_tracks_video_asset_id'), table_name='audio_tracks')
    op.drop_index(op.f('ix_audio_tracks_project_id'), table_name='audio_tracks')
    op.drop_index(op.f('ix_audio_tracks_id'), table_name='audio_tracks')
    op.drop_table('audio_tracks')
    op.drop_index(op.f('ix_video_assets_project_id'), table_name='video_assets')
    op.drop_index(op.f('ix_video_assets_id'), table_name='video_assets')
    op.drop_table('video_assets')
    op.drop_index(op.f('ix_export_jobs_status'), table_name='export_jobs')
    op.drop_index(op.f('ix_export_jobs_project_id'), table_name='export_jobs')
    op.drop_index(op.f('ix_export_jobs_id'), table_name='export_jobs')
    op.drop_table('export_jobs')
    op.drop_index(op.f('ix_background_music_project_id'), table_name='background_music')
    op.drop_index(op.f('ix_background_music_id'), table_name='background_music')
    op.drop_table('background_music')
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
